version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fridge-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Fr1dge!p@ssw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - fridge_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Fr1dge!p@ssw0rd' -Q 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s







volumes:
  fridge_sql_data: